-- Initialize explicitly after migration: select public.initialize_game_patch('REAL_VERSION');
create type public.game_patch_status as enum ('draft','active','archived');
create table public.game_patches(id bigint generated by default as identity primary key,version text not null unique check(btrim(version)<>''),status public.game_patch_status not null default 'draft',release_at timestamptz,created_at timestamptz not null default now());
create unique index game_patches_version_ci_idx on public.game_patches(lower(version));
create unique index game_patches_one_active_idx on public.game_patches((status)) where status='active';
create table public.game_state(id smallint primary key default 1 check(id=1),active_patch_id bigint not null references public.game_patches(id),updated_at timestamptz not null default now());
create table public.champion_patch_stats(champion_id text not null,patch_id bigint not null references public.game_patches(id) on delete cascade,data jsonb not null check(jsonb_typeof(data)='object'),primary key(champion_id,patch_id));
create table public.item_patch_data(item_id text not null,patch_id bigint not null references public.game_patches(id) on delete cascade,data jsonb not null check(jsonb_typeof(data)='object'),primary key(item_id,patch_id));
create table public.rune_patch_data(rune_id text not null,patch_id bigint not null references public.game_patches(id) on delete cascade,data jsonb not null check(jsonb_typeof(data)='object'),primary key(rune_id,patch_id));

create function public.initialize_game_patch(p_version text) returns bigint language plpgsql security definer set search_path=pg_catalog,public as $$
declare v bigint;
begin
 if nullif(btrim(p_version),'') is null then raise exception 'Patch version is required'; end if;
 if exists(select 1 from public.game_state) then raise exception 'Game patching is already initialized'; end if;
 insert into public.game_patches(version,status) values(btrim(p_version),'active') returning id into v;
 insert into public.champion_patch_stats select id::text,v,to_jsonb(c)-array['id','name','image_url','image_url_card','external_id','original_name'] from public.champions c;
 insert into public.item_patch_data select id::text,v,to_jsonb(i)-array['id','name','image_url'] from public.wr_items i;
 insert into public.rune_patch_data select id::text,v,to_jsonb(r)-array['id','name','image_url','branch','group'] from public.runes r;
 insert into public.game_state(id,active_patch_id) values(1,v); return v;
end $$;

create function public.create_patch_from_current(p_version text) returns bigint language plpgsql security definer set search_path=pg_catalog,public as $$
declare old_id bigint; new_id bigint;
begin
 if nullif(btrim(p_version),'') is null then raise exception 'Patch version is required'; end if;
 select active_patch_id into old_id from public.game_state where id=1 for update;
 if old_id is null then raise exception 'No active patch is configured'; end if;
 if exists(select 1 from public.game_patches where lower(version)=lower(btrim(p_version))) then raise exception 'Patch version already exists'; end if;
 insert into public.game_patches(version) values(btrim(p_version)) returning id into new_id;
 insert into public.champion_patch_stats select champion_id,new_id,data from public.champion_patch_stats where patch_id=old_id;
 insert into public.item_patch_data select item_id,new_id,data from public.item_patch_data where patch_id=old_id;
 insert into public.rune_patch_data select rune_id,new_id,data from public.rune_patch_data where patch_id=old_id;
 return new_id;
end $$;

create function public.validate_patch(p_patch_id bigint) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare e jsonb:='[]'; ca int;ce int;ia int;ie int;ra int;re int;
begin
 if not exists(select 1 from public.game_patches where id=p_patch_id) then return jsonb_build_object('valid',false,'errors',jsonb_build_array('Patch does not exist')); end if;
 select count(*) into ce from public.champions; select count(*) into ca from public.champion_patch_stats where patch_id=p_patch_id;
 select count(*) into ie from public.wr_items; select count(*) into ia from public.item_patch_data where patch_id=p_patch_id;
 select count(*) into re from public.runes; select count(*) into ra from public.rune_patch_data where patch_id=p_patch_id;
 select e||coalesce(jsonb_agg('Missing champion '||c.id::text),'[]') into e from public.champions c where not exists(select 1 from public.champion_patch_stats d where d.patch_id=p_patch_id and d.champion_id=c.id::text);
 select e||coalesce(jsonb_agg('Unknown champion '||d.champion_id),'[]') into e from public.champion_patch_stats d where d.patch_id=p_patch_id and not exists(select 1 from public.champions c where c.id::text=d.champion_id);
 select e||coalesce(jsonb_agg('Missing item '||i.id::text),'[]') into e from public.wr_items i where not exists(select 1 from public.item_patch_data d where d.patch_id=p_patch_id and d.item_id=i.id::text);
 select e||coalesce(jsonb_agg('Unknown item '||d.item_id),'[]') into e from public.item_patch_data d where d.patch_id=p_patch_id and not exists(select 1 from public.wr_items i where i.id::text=d.item_id);
 select e||coalesce(jsonb_agg('Missing rune '||r.id::text),'[]') into e from public.runes r where not exists(select 1 from public.rune_patch_data d where d.patch_id=p_patch_id and d.rune_id=r.id::text);
 select e||coalesce(jsonb_agg('Unknown rune '||d.rune_id),'[]') into e from public.rune_patch_data d where d.patch_id=p_patch_id and not exists(select 1 from public.runes r where r.id::text=d.rune_id);
 return jsonb_build_object('valid',jsonb_array_length(e)=0,'champions',jsonb_build_object('actual',ca,'expected',ce),'items',jsonb_build_object('actual',ia,'expected',ie),'runes',jsonb_build_object('actual',ra,'expected',re),'errors',e);
end $$;
create function public.validate_patch_by_version(p_version text) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$ declare v bigint; begin select id into v from public.game_patches where lower(version)=lower(btrim(p_version)); if v is null then return jsonb_build_object('valid',false,'errors',jsonb_build_array('Patch does not exist')); end if; return public.validate_patch(v); end $$;

create function public.activate_patch(p_patch_id bigint) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare validation jsonb; old_id bigint;
begin
 perform pg_advisory_xact_lock(724853); validation:=public.validate_patch(p_patch_id);
 if not(validation->>'valid')::boolean then raise exception 'Patch validation failed: %',validation->'errors'; end if;
 select active_patch_id into old_id from public.game_state where id=1 for update;
 update public.game_patches set status='archived' where id=old_id and id<>p_patch_id;
 update public.game_patches set status='active',release_at=coalesce(release_at,now()) where id=p_patch_id;
 update public.game_state set active_patch_id=p_patch_id,updated_at=now() where id=1;
 return jsonb_build_object('active_patch_id',p_patch_id,'previous_patch_id',old_id);
end $$;
create function public.activate_patch_by_version(p_version text) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$ declare v bigint; begin select id into v from public.game_patches where lower(version)=lower(btrim(p_version)); if v is null then raise exception 'Patch version does not exist'; end if; return public.activate_patch(v); end $$;

create view public.current_champions with(security_invoker=true) as select (jsonb_populate_record(c,d.data)).*,p.id patch_id,p.version patch_version from public.champions c join public.game_state s on s.id=1 join public.game_patches p on p.id=s.active_patch_id join public.champion_patch_stats d on d.patch_id=p.id and d.champion_id=c.id::text;
create view public.current_wr_items with(security_invoker=true) as select (jsonb_populate_record(i,d.data)).*,p.id patch_id,p.version patch_version from public.wr_items i join public.game_state s on s.id=1 join public.game_patches p on p.id=s.active_patch_id join public.item_patch_data d on d.patch_id=p.id and d.item_id=i.id::text;
create view public.current_runes with(security_invoker=true) as select (jsonb_populate_record(r,d.data)).*,p.id patch_id,p.version patch_version from public.runes r join public.game_state s on s.id=1 join public.game_patches p on p.id=s.active_patch_id join public.rune_patch_data d on d.patch_id=p.id and d.rune_id=r.id::text;

alter table public.game_patches enable row level security; alter table public.game_state enable row level security; alter table public.champion_patch_stats enable row level security; alter table public.item_patch_data enable row level security; alter table public.rune_patch_data enable row level security;
create policy game_patches_read on public.game_patches for select to anon,authenticated using(true); create policy game_state_read on public.game_state for select to anon,authenticated using(true);
create policy champion_active_read on public.champion_patch_stats for select to anon,authenticated using(patch_id=(select active_patch_id from public.game_state where id=1));
create policy item_active_read on public.item_patch_data for select to anon,authenticated using(patch_id=(select active_patch_id from public.game_state where id=1));
create policy rune_active_read on public.rune_patch_data for select to anon,authenticated using(patch_id=(select active_patch_id from public.game_state where id=1));
grant select on public.game_patches,public.game_state,public.champion_patch_stats,public.item_patch_data,public.rune_patch_data,public.current_champions,public.current_wr_items,public.current_runes to anon,authenticated;
revoke all on function public.initialize_game_patch(text),public.create_patch_from_current(text),public.validate_patch(bigint),public.validate_patch_by_version(text),public.activate_patch(bigint),public.activate_patch_by_version(text) from public,anon,authenticated;
grant execute on function public.initialize_game_patch(text),public.create_patch_from_current(text),public.validate_patch(bigint),public.validate_patch_by_version(text),public.activate_patch(bigint),public.activate_patch_by_version(text) to postgres,service_role;
